### PR TITLE
Removed 3rd party font dependency & switched to local files

### LINKED ISSUE #22: host 3rd party font locally
According to our [code standards](https://github.com/codidact/core/wiki/Code-standards:-HTML#26-fonts). all fonts should be hosted locally.

Download the google font specified in the index.html file and load it into the stylesheet, replacing the remote hosted font

### PR DESCRIPTION
**Pull request by kieranirving**
Fixes #22

### CODE REVIEW

**Comment by ranolfi** [comment]
Same as https://github.com/codidact/landing-page/pull/29#issuecomment-580079865.

**Comment by kieranirving** [comment]
@ranolfi fixed.

**Comment by ranolfi** [comment]
Thanks for tackling this one.

Can you consider sourcing from https://github.com/RedHatOfficial/RedHatFont/tree/master/webfonts instead? Upload the WOFF2 fonts only. They add up to 227,2 KiB, compared to the TTF ones (601,5 KiB). If you do, please rename the `Red_Hat_Display` dir to match the source, and add a note to the commit message with the above link.

I don't know if you can even upload only the typeface(s) which are needed instead of *all* of them, but if yes, it seems to me that's desirable.

**Comment by ranolfi** [comment]
1. Something went wrong there; there are some unrelated changes in your commit f5082adf - deleted/added images. I suppose you'll have to amend the commit, uncheck all unrelated changes, force-push and then revert your local changes by doing a hard-reset (not needed if you plan to delete the branch right after).

2. According to the [committing guidelines](https://github.com/codidact/core/wiki/Committing-guidelines), commit messages should be in the infinitive (that would be "Remove", instead of "Removed").

3. Since you're amending anyway, I suggest an even more concise commit message. Either:

   > - Remove 3rd-party font dependency
    > - Replace 3rd-party font dependency by local file
    > - Make 3rd-party font dependency local
    > - Add 3rd-party font dependency as local asset to conform to HTML standards

    Then, optionally, add a line break and specify which section and rule of the coding standard this is conforming to. The point is for someone to be able to figure out exactly \_why\_ this commit exists _without_ needing to actually consult the standards.

1 and 2 are requirements, 3 is a suggestion.

Thanks :)

**Pull request closed without merging**
