### PR TITLE
My own attempt at #32.

### PR DESCRIPTION
**Pull request by galegosimpatico**
This is rendering in my end like:

Screenshot 2020-08-22 at 23 05 07

:)

### CODE REVIEW

**Comment by ArtOfCode-** [comment]
Still needs the actual FAQ updating, but that needs someone to write it.

**Comment by ArtOfCode-** [comment]
New FAQ is done. Can we point this at `https://raw.githubusercontent.com/codidact/docs/master/User-Help/CodidactMainPageFAQ.md` instead of the Gist link so that it picks up the right one?

**Comment by galegosimpatico** [comment]
Done and re pushed to https://galegosimpatico.github.io/codidact-landing-page/, requires further changes.

**Comment by galegosimpatico** [comment]
Done, https://github.com/codidact/landing-page/pull/53/commits/ee572e0539db05d15e40dc52469afbfb9aa20a95 live at https://galegosimpatico.github.io/codidact-landing-page/.

**Comment by galegosimpatico** [comment]
I guess JS update comes from https://github.com/codidact/landing-page/commit/2206e3 https://github.com/codidact/landing-page/commit/343046 etc.

![https://i0.kym-cdn.com/entries/icons/original/000/008/342/ihave.jpg][0]

[0]: https://i0.kym-cdn.com/entries/icons/original/000/008/342/ihave.jpg

**Pull request merged**
