### PR TITLE
Css grid

### PR DESCRIPTION
**Pull request by mattjbrent**
A very large MR

This is the basis for the new landing page design.

It uses a basic CSS grid using flex. Because images were previously placeholder, images in sections have been omitted. Once decent images have been sourced we can look at pulling them in a separate PR.

Because of how divergent master is from the branch - we will probably be best manually adding any required changes from master then force merging into master and pushing.

This PR represents a lot of work, and its a little messy in places so please be kind. I figured it would be best to get this out as soon as possible and get other people fixing on top of it. I'm also thinking if we can make the merge after any major fixes and fast follow just so we can get this up on production.

Also - sorry about the weird merge commits in early December. You can ignore those.

### CODE REVIEW

**Comment by ArtOfCode-** [comment]
Can you throw up a screenshot of how this looks? It's hard to get an idea of where this has got to just from looking at the code.

**Comment by roberrrt-s** [comment]
Screenshot 2020-01-17 at 13 44 40
Screenshot 2020-01-17 at 13 44 35
Screenshot 2020-01-17 at 13 44 28
Screenshot 2020-01-17 at 13 44 13

@luap42 @ArtOfCode-

**Comment by ArtOfCode-** [comment]
Ready to merge @mattjbrent? If this is good to go, I'll run a manual force merge.

**Comment by luap42** [comment]
Looks good, one comment though:

The GitHub icon in the header is quite bright and has probably a bad contrast.

**Comment by mattjbrent** [comment]
@ArtOfCode- yeah lets get this merged. We can always make fixes later as this is a low-risk merge (we arent deploying into master yet)

my aim once this is merged into new-design is to get webpack production build finished and get this deployed out live.

**Pull request merged**
