### PR TITLE
Mattbrent/webpack prod

### PR DESCRIPTION
**Pull request by mattjbrent**
Adds a basic Webpack production build.

Also removed src/assets as i felt like it was unnecessary (src already is assets)
some small fixes as i went to stylelint errors
also gitignored dist/css and dist/js so that built dist files aren't tracked. build files will be built on CD platform (i suggested a potential of buddy.works - they are free for opensource)

### CODE REVIEW

**Comment by mattjbrent** [comment]
If you're ok with it we could set up a free account on buddy.works and set up a simple pipeline?

**Comment by ranolfi** [comment]
I'd also like to suggest an improved commit message to 54baaabf (which currently says: "_added correct path to dist/assets/css and js_" to make clear it is added *to gitignore*. A simple `gitignore: ` commit message prefix would suffice.

Finally, per the [committing guidelines](https://github.com/codidact/core/wiki/Committing-guidelines), commit messages should be in infinitive (i.e. verbs should be "add", "change", "disable").  
That said I'm not blocking the merge for this reason at this time. (But an interactive rebase should be straightforward). Your call.

**Comment by mattjbrent** [comment]
@ranolfi Yeah - sorry about those commits - i fixed them and rebased to new-design also.

**Comment by ranolfi** [comment]
@mattjbrent, thanks! In any case, the hold off here is actually the removal of the `dist` subdirs - we should prefer to discuss and implement a change in the deployment strategy separately, rather than at this time. Can you resubmit without 09dd6afd?

Oh and just noticed something else - there still exists `src/assets/img/3rd-party/logo-github-white.png`. Maybe an oversight?

**Comment by mattjbrent** [comment]
@ranolfi are you asking to remove the build from `dist` and have it build in to the top directory? That's a little more involved than removing that last commit. (but still not a lot of work)

So moving contents of dist into the top directory then modifying Webpack config to build into assets?

**Comment by ranolfi** [comment]
> @ranolfi are you asking to remove the build from `dist` and have it build in to the top directory? That's a little more involved than removing that last commit. (but still not a lot of work)
> 
> So moving contents of dist into the top directory then modifying Webpack config to build into assets?

No, not that. We'll keep deploying the `dist` directory; the point is that it should contain everything required for the site to work. **But, my bad** - I overlooked the fact that the ignored dirs are created by the build script, so all good.

Please just take a look at the file under `src/assets/img/3rd-party/` that I mentioned. Is it dangling?

@mattjbrent

**Comment by mattjbrent** [comment]
@ranolfi no i dont think its a dangling commit. The extraneous file was probably accidentally added in when I rebased to new-design. Not sure how I missed that one :|

Either way - good catch. ill just remove it in a commit now

**Comment by ranolfi** [comment]
Thank you!

**Pull request merged**
